#!/bin/bash

function log-debug() {
    if [ "${GO_INIT_DEBUG}" == "1" ] || [ "${GO_INIT_DEBUG}" == "true" ] || [ "${GO_INIT_DEBUG}" == "yes" ] || [ "${GO_INIT_DEBUG}" == "y" ]; then
        echo "[DEBUG]: $@"
    fi
}

function get-user-by-id() {
    local user_id=$1
    cat /etc/passwd | awk -F: '{print $1":"$3":"}' | grep ":${user_id}:"
    return $?
}

function delete-user-if-exists() {
    local user_name=$1
    local user_id=$2
    local existing_user=$(get-user-by-id ${user_id} | awk -F: '{print $1}')

    if [ -n "${existing_user}" ] && [ "${existing_user}" != "${user_name}" ]; then
        userdel -r ${existing_user}
    fi
}

ARGS=()
while [ -n "${1}" ]; do
    case "${1}" in
        --go-init-debug|-go-init-debug)
            GO_INIT_DEBUG=true
            shift
            ;;
        *)
            ARGS+=("${1}")
            shift
            ;;
    esac
done

if [ -z "${ARGS[*]}" ]; then
    ARGS+=('bash')
fi
log-debug "Args: ${ARGS[@]}"

USER_ID=$(id -u)
if [ -z "${GOUID}" ]; then
    GOUID=${USER_ID}
fi

if [ "${USER_ID}" != "0" ]; then
    export PS1='[\w]$ '
    if ! get-user-by-id ${USER_ID}; then
        userdel -r ${GOUSER}
        useradd -Umou ${USER_ID} ${GOUSER}
    fi
    EXECUTABLE=${ARGS[@]}
    log-debug "Running directly as: $(id)"
elif [ -n "${GOUID}" ] && [ "${GOUID}" != "0" ]; then
    export PS1='[\w]$ '
    delete-user-if-exists ${GOUSER} ${GOUID}
    usermod -ou ${GOUID} ${GOUSER}
    EXECUTABLE=("su-exec" "${GOUSER}" "${ARGS[@]}")
    log-debug "Dropping privileges to: $(id ${GOUSER})"
else
    export PS1='[\w]# '
    EXECUTABLE=${ARGS[@]}
    log-debug "Running directly as: $(id)"
fi

log-debug "Executing: ${EXECUTABLE[@]}"
exec ${EXECUTABLE[@]}
